### ISSUE TITLE
train.mirror_augment

### ISSUE THREAD

**Issue by happyhugo** [WilliamHMLeong/Pix2PixPGGAN-tensorflow#1]
In config.py .  train.mirror_augment should be false. otherwise the training pair is not right
Did you upload your code about  U-Net Structure?
I just found the None U-Net Structure.

**Comment by WilliamHMLeong** [comment]
I am very sorry, I will fix it later as I am very busy for these weeks.

**Comment by manvirvirk** [comment]
What is the dataset directory?

**Comment by manvirvirk** [comment]
Hi, when i m running dataset_tool.py it is showing adding 0 images, no tf-record file is generated. Can you please help?
